getLoader2Args: getLoader2Args.o
	arm-elf-gcc getLoader2Args.c -o getLoader2AutoExec -elf2flt
#getLoader2Args.o: getLoader2Args.c
clean:
	rm -f getLoader2AutoExec getLoader2AutoExec.gdb *.o
.PHONY: clean
